export interface IPokemon{
    abilities: any[],
      base_experience: number,
      forms: object[],
      game_indices: object[],
      height: number,
      held_items: object[],
      id: number,
      is_default: boolean,
      location_area_encounters: string,
      moves: object[],
      name: string,
      order: number,
      past_types:object[],
      species: any,
      sprites: any,
      stats: object[],
      types: any[],
      weight: number,
}